### ISSUE TITLE
[Feature 1.19.2]: Add support for Fabric Waystone's Void Totem

### ISSUE THREAD

**Issue by kingkuys2123** [TheIllusiveC4/CurioOfUndying#19] opened 2023-01-08 03:25 UTC
### What is the new feature or improvement?

Add support for [Fabric Waystone's](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) void totem :)

**Comment by TheIllusiveC4** [comment] 2023-01-14 09:58
Duplicate of https://github.com/illusivesoulworks/charmofundying/issues/13

**Closed as not planned by TheIllusiveC4** 2023-01-14 09:58 UTC
Labels: status: duplicate, type: enhancement
