### ISSUE TITLE
[Bug]: crash at opening the game

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/CurioOfUndying#30] opened 2023-08-25 11:24 UTC
### Minecraft Version

1.18.2

### What happened?

It seems like an issue related to i18nupdatemod.

### How do you trigger this bug?

1.starting game
2.crash

### Loader

Forge

### Loader Version

forgeVersion-40.2.10

### Mod Version

curioofundying-forge-1.18-5.3.0.0

### Relevant Log Outputs

[https://pastebin.com/NQ9UPBPW](url)
The log seems incomplete, but that's all I have.

**Comment by TheIllusiveC4** [comment] 2023-10-29 05:22
From what I can tell, this is probably not an issue with this mod. However, I'm not sure exactly what the cause is. Based on my research, I would suggest removing i18nupdatemod and see if that resolves it. If it does, it might need to be resolved by i18nupdatemod. If that doesn't work, I would then also suggest reinstalling your Forge instance and see if that helps.

**Closed as completed by TheIllusiveC4** 2023-10-29 05:22 UTC
Labels: type: bug, status: resolved
